[core]
db_path = "../OpenFusion/database.db"
port = 8080

# App-terminated TLS, as opposed to proxy-terminated TLS.
[app_tls]
cert_path = "cert.pem"
key_path = "key.pem"
port = 443

[rankinfo]
route = "/getranks"
placeholders = false

[auth]
route = "/auth"
secret_path = "secret"
valid_secs = 604_800 # one week

[cookie]
route = "/cookie"
valid_secs = 60
