[core]
db_path = "../OpenFusion/database.db"
port = 80

[tls]
cert_path = "cert.pem" # app-level TLS only
key_path = "key.pem" # app-level TLS only
port = 443

[rankinfo]
route = "/getranks"
placeholders = true

[auth]
route = "/auth"
secret_path = "secret"
valid_secs = 604_800 # one week

[cookie]
route = "/cookie"
valid_secs = 60
