[core]
db_path = "../OpenFusion/database.db"
port = 8888

[tls]
cert_path = "cert.pem" # app-level TLS only
key_path = "key.pem" # app-level TLS only
port = 4433

[game]
# GUID of the game versions compatible the OpenFusion server.
# If this identifies any custom versions, you should include the
# manifest for each one in the `versions` directory.
versions = ["ec8063b2-54d4-4ee1-8d9e-381f5babd420"]
# Hostname and login port of the OpenFusion server to advertise
login_address = "play.myserver.xyz:23000"

[monitor]
route = "/status"
monitor_ip = "127.0.0.1:8003"

[rankinfo]
route = "/getranks"
placeholders = true

[auth]
route = "/auth"
secret_path = "secret"
valid_secs = 604_800 # one week

[cookie]
route = "/cookie"
valid_secs = 60
