[core]
db_path = "../OpenFusion/database.db"
port = 80

[tls]
cert_path = "cert.pem"
key_path = "key.pem"
port = 443

[rankinfo]
route = "/getranks"
placeholders = true

[auth]
route = "/auth"
