[core]
server_name = "My OpenFusion Server"
public_url = "api.example.xyz"
db_path = "../OpenFusion/database.db"
template_dir = "./templates"
port = 8888

[tls]
cert_path = "cert.pem" # app-level TLS only
key_path = "key.pem" # app-level TLS only
port = 4433

[email]
# SMTP credentials, etc. will be here once email is implemented

[game]
# GUID of the game versions compatible the OpenFusion server.
# If this identifies any custom versions, you should include the
# manifest for each one in the `versions` directory.
versions = ["ec8063b2-54d4-4ee1-8d9e-381f5babd420"]
# Hostname and login port of the OpenFusion server to advertise
login_address = "play.myserver.xyz:23000"
# If you have your own loading bar assets you wanna use (in static/launcher/loading), set true
custom_loading_screen = false

[monitor]
route = "/status"
monitor_ip = "127.0.0.1:8003"

[moderation]
namereq_route = "/namereq"

[rankinfo]
route = "/getranks"
placeholders = true

[account]
route = "/account"

## Account registration
register_subroute = "/register"
account_level = 99
require_email = false
# If this is true, accounts will not be created until after email verification.
# Note that all email verification requests expire when the API server is shut off.
require_email_verification = false

## Email verification
email_verification_subroute = "/verify"
email_verification_valid_secs = 3_600 # one hour

## Update account info
update_email_subroute = "/update/email"
update_password_subroute = "/update/password"

[auth]
route = "/auth"
refresh_subroute = "/session"
secret_path = "secret"
# Session tokens are used to authenticate requests. They should be short-lived.
# Refresh tokens are used to generate new session tokens. They should be long-lived and cached by clients.
valid_secs_refresh = 604_800 # one week
valid_secs_session = 900 # 15 minutes

[cookie]
route = "/cookie"
valid_secs = 60

[legacy]
# These routes are used in the case of a legacy web-browser based game clients such 
# as Electron. If you do not use these, you can remove this section of the config.
# When multiple versions are provided, legacy endpoints will use the first one.
index_route = "/index.html"
assetinfo_route = "/assetInfo.php"
logininfo_route = "/loginInfo.php"
